/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoresumenes.Interfaces;

import javax.swing.JOptionPane;
import proyectoresumenes.AVLTreeAutor;
import proyectoresumenes.AVLTreePalabraClave;
import proyectoresumenes.PalabraFrecuencia;
import proyectoresumenes.Resumen;
import proyectoresumenes.Sistema;
import proyectoresumenes.TablaHashResumenes;

/**
 *
 * @author Andres
 */
public class AnalizarResumen extends javax.swing.JFrame {

    static AVLTreeAutor avlA;
    static AVLTreePalabraClave avlPC;
    static TablaHashResumenes tablahash;

    /**
     * Creates new form Principal
     */
    public AnalizarResumen(AVLTreeAutor avlA, AVLTreePalabraClave avlPC, TablaHashResumenes tablahash) {
        initComponents();
        this.setVisible(true);
        this.avlA = avlA;
        this.avlPC = avlPC;
        this.tablahash = tablahash;
        Sistema sistema = new Sistema(avlA, avlPC, tablahash);

        String[] titulosOrdenados = sistema.listarTitulosOrdenados();
        for (String titulo : titulosOrdenados) {
            this.opciones.addItem(titulo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        opciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yet R", 1, 24)); // NOI18N
        jLabel1.setText("Analisis:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jButton1.setFont(new java.awt.Font("Yet R", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 50, 40));

        opciones.setFont(new java.awt.Font("Yet R", 1, 18)); // NOI18N
        jPanel1.add(opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 290, 40));

        salida.setColumns(20);
        salida.setFont(new java.awt.Font("Yet R", 2, 14)); // NOI18N
        salida.setRows(5);
        jScrollPane1.setViewportView(salida);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 530, 260));

        jButton2.setFont(new java.awt.Font("Yet R", 1, 18)); // NOI18N
        jButton2.setText("ANALIZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 130, 40));

        jLabel2.setFont(new java.awt.Font("Yet R", 1, 48)); // NOI18N
        jLabel2.setText("Analizar Resumen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yet R", 1, 24)); // NOI18N
        jLabel3.setText("Selecciona el Resumen:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal(avlA, avlPC, tablahash);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String titulo = this.opciones.getSelectedItem().toString();
            Sistema sistema = new Sistema(avlA, avlPC, tablahash);

            Resumen rAnalizar = sistema.buscarResumenPorTitulo(titulo);
            
            
            
            if (rAnalizar != null) {
            
            PalabraFrecuencia[] frecuencias = sistema.analizarResumen(rAnalizar);
            Sistema.ordenarfrFRECUENCIAS(frecuencias);
            this.salida.setText(rAnalizar.analizar());
            for (int i = 0; i < frecuencias.length; i++) {
                PalabraFrecuencia pf = frecuencias[i];
                if (pf.frecuencia > 0) {
                    this.salida.setText(this.salida.getText() + "  - " + pf.palabra + ": " + pf.frecuencia + " veces");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Resumen no encontrado");
        }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalizarResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalizarResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalizarResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalizarResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalizarResumen(avlA, avlPC, tablahash).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> opciones;
    private javax.swing.JTextArea salida;
    // End of variables declaration//GEN-END:variables
}
