/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoresumenes.Interfaces;

import javax.swing.JOptionPane;
import proyectoresumenes.AVLTreeAutor;
import proyectoresumenes.AVLTreePalabraClave;
import proyectoresumenes.Lista;
import proyectoresumenes.PalabraFrecuencia;
import proyectoresumenes.Resumen;
import proyectoresumenes.Sistema;
import proyectoresumenes.TablaHashResumenes;

/**
 *
 * @author Andres
 */
public class BuscarAutor extends javax.swing.JFrame {

    static AVLTreeAutor avlA;
    static AVLTreePalabraClave avlPC;
    static TablaHashResumenes tablahash;

    /**
     * Creates new form Principal
     */
    public BuscarAutor(AVLTreeAutor avlA, AVLTreePalabraClave avlPC, TablaHashResumenes tablahash) {
        initComponents();
        this.setVisible(true);
        this.avlA = avlA;
        this.avlPC = avlPC;
        this.tablahash = tablahash;
        Sistema sistema = new Sistema(avlA, avlPC, tablahash);

        String[] autoresOrdenados = sistema.obtenerListaAutoresOrdenada();
        for (String autor : autoresOrdenados) {
            this.opciones.addItem(autor);
        }
        this.opciones1.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        opciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        opciones1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yet R", 1, 48)); // NOI18N
        jLabel1.setText("Buscar Resumenes por Autor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jButton1.setFont(new java.awt.Font("Yet R", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 50, 40));

        opciones.setFont(new java.awt.Font("Yet R", 1, 18)); // NOI18N
        opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesActionPerformed(evt);
            }
        });
        jPanel1.add(opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 240, 40));

        salida.setColumns(20);
        salida.setFont(new java.awt.Font("Yet R", 2, 14)); // NOI18N
        salida.setRows(5);
        jScrollPane1.setViewportView(salida);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 700, 280));

        jButton2.setFont(new java.awt.Font("Yet R", 1, 18)); // NOI18N
        jButton2.setText("ANALIZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 130, 40));

        opciones1.setFont(new java.awt.Font("Yet R", 1, 18)); // NOI18N
        opciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opciones1ActionPerformed(evt);
            }
        });
        jPanel1.add(opciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 270, 40));

        jLabel3.setFont(new java.awt.Font("Yet R", 1, 24)); // NOI18N
        jLabel3.setText("Escoge el Resumen:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yet R", 1, 24)); // NOI18N
        jLabel4.setText("Escoge el Autor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal(avlA, avlPC, tablahash);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String titulo = this.opciones1.getSelectedItem().toString();
            Sistema sistema = new Sistema(avlA, avlPC, tablahash);

            Resumen rAnalizar = sistema.buscarResumenPorTitulo(titulo);

            if (rAnalizar != null) {

                PalabraFrecuencia[] frecuencias = sistema.analizarResumen(rAnalizar);
                Sistema.ordenarfrFRECUENCIAS(frecuencias);
                this.salida.setText(rAnalizar.analizar());
                for (int i = 0; i < frecuencias.length; i++) {
                    PalabraFrecuencia pf = frecuencias[i];
                    if (pf.frecuencia > 0) {
                        this.salida.setText(this.salida.getText() + "  - " + pf.palabra + ": " + pf.frecuencia + " veces\n");
                    }
                }
                this.salida.setText("\nCuerpo: \n" + rAnalizar.cuerpo);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Resumen no encontrado");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void opciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opciones1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_opciones1ActionPerformed

    private void opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesActionPerformed
        // TODO add your handling code here:
        String autor = this.opciones.getSelectedItem().toString();
        Sistema sistema = new Sistema(avlA, avlPC, tablahash);
        this.opciones1.removeAllItems();
        Lista listaAutor = sistema.buscarPorAutor(autor);

        String[] titulos = listaAutor.obtenerTitulos();
        if (titulos.length == 0) {
            JOptionPane.showMessageDialog(rootPane, "No se encontraron resumenes para el autor");
        }

        Sistema.ordenaraALFABETICO(titulos);

        for (String titulo : titulos) {
            this.opciones1.addItem(titulo);
        }
    }//GEN-LAST:event_opcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarAutor(avlA, avlPC, tablahash).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> opciones;
    private javax.swing.JComboBox<String> opciones1;
    private javax.swing.JTextArea salida;
    // End of variables declaration//GEN-END:variables
}
