/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoresumenes.Interfaces;

import javax.swing.JOptionPane;
import proyectoresumenes.AVLTreeAutor;
import proyectoresumenes.AVLTreePalabraClave;
import proyectoresumenes.Lista;
import proyectoresumenes.PalabraFrecuencia;
import proyectoresumenes.Resumen;
import proyectoresumenes.Sistema;
import proyectoresumenes.TablaHashResumenes;

/**
 *
 * @author Andres
 */
public class ListarPC extends javax.swing.JFrame {

    static AVLTreeAutor avlA;
    static AVLTreePalabraClave avlPC;
    static TablaHashResumenes tablahash;

    /**
     * Creates new form Principal
     */
    public ListarPC(AVLTreeAutor avlA, AVLTreePalabraClave avlPC, TablaHashResumenes tablahash) {
        initComponents();
        this.setVisible(true);
        this.avlA = avlA;
        this.avlPC = avlPC;
        this.tablahash = tablahash;
        Sistema sistema = new Sistema(avlA, avlPC, tablahash);

        String[] clavesOrdenadas = sistema.listarPalabrasClaveOrdenadas();
        for (String clave : clavesOrdenadas) {
            this.opciones.addItem(clave);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        opciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yet R", 1, 48)); // NOI18N
        jLabel1.setText("Lista de Palabras Clave");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jButton1.setFont(new java.awt.Font("Yet R", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 50, 40));

        opciones.setFont(new java.awt.Font("Yet R", 1, 18)); // NOI18N
        jPanel1.add(opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 310, 40));

        salida.setColumns(20);
        salida.setFont(new java.awt.Font("Yet R", 2, 14)); // NOI18N
        salida.setRows(5);
        jScrollPane1.setViewportView(salida);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 670, 260));

        jButton2.setFont(new java.awt.Font("Yet R", 1, 18)); // NOI18N
        jButton2.setText("DETALLES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal(avlA, avlPC, tablahash);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String titulo = this.opciones.getSelectedItem().toString();

            Sistema sistemaActual = new Sistema(this.avlA, this.avlPC, this.tablahash);

            Lista rAnalizar = sistemaActual.buscarPorPalabraClave(titulo);
            String a = ""; 
            if (rAnalizar != null) {
                
                String reporte = sistemaActual.generarReporteFrecuenciaPorPalabra(rAnalizar, titulo);
                a = "Resultados para la palabra clave: " + titulo + "\n"
                        + "--------------------------------------------------\n"
                        + reporte;
                this.salida.setText(a);
            } else {
                
                a = "No se encontraron resúmenes para la palabra clave: " + titulo;
                this.salida.setText(a);
            }
        } catch (Exception e) {
            // Manejo de errores
            System.err.println("Error al generar reporte: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarPC(avlA, avlPC, tablahash).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> opciones;
    private javax.swing.JTextArea salida;
    // End of variables declaration//GEN-END:variables
}
